// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9TlYgbkId9fhl__s8fmydTy_7exiWqJ4',
    appId: '1:1075899688294:web:a11dafa76f7aa987a594a7',
    messagingSenderId: '1075899688294',
    projectId: 'multi-vendor-ecommerce-f405b',
    authDomain: 'multi-vendor-ecommerce-f405b.firebaseapp.com',
    storageBucket: 'multi-vendor-ecommerce-f405b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvHJfe3miZW4BuJqXgc2NQ2RFC-5iYagk',
    appId: '1:1075899688294:android:3aa17968aa7849cea594a7',
    messagingSenderId: '1075899688294',
    projectId: 'multi-vendor-ecommerce-f405b',
    storageBucket: 'multi-vendor-ecommerce-f405b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANuU1K4oi-dbEpSShf_jM-a3fX6xhV7Vk',
    appId: '1:1075899688294:ios:c01f8291fb5c61cca594a7',
    messagingSenderId: '1075899688294',
    projectId: 'multi-vendor-ecommerce-f405b',
    storageBucket: 'multi-vendor-ecommerce-f405b.appspot.com',
    iosClientId: '1075899688294-434dd3lisdt68brqbc4u64vqbjhh0nqj.apps.googleusercontent.com',
    iosBundleId: 'com.appsbymuk.multiVendor',
  );
}
